"""
gemini_service.py — Gemini API wrapper for Phase 1.

Gemini's only job here is LABELING, not editing:
  - Input: clean binary skeleton image (walls only, no furniture)
  - Output: room types, opening locations (doors/windows at wall gaps)

All image processing is handled by processing.py before this is called.
"""

import asyncio
import base64
import json
import logging
import time
from pathlib import Path
from typing import Optional, Tuple, Any

import os
from google import genai
from google.genai import types

from app.config import get_settings
from app.services.processing import (
    build_wall_skeleton,
    validate_openings,
    render_structural,
)

logger = logging.getLogger(__name__)

GEMINI_MODEL = "gemini-2.5-flash"
VERTEX_PROJECT = "gen-lang-client-0434074228"
VERTEX_LOCATION = "us-central1"

LABELING_PROMPT = """You are analyzing a skeletonized architectural floor plan.
This image was generated by a computer vision pipeline — it contains ONLY the 1-pixel
skeleton of structural walls. There are no furniture, no dimension lines, no text.
Every black line you see IS a wall or wall edge.

Return ONLY a JSON object. No markdown. No explanation.

{
  "scale_references": [
    {"value": "4.50", "unit": "m", "bbox": [x1, y1, x2, y2]}
  ],
  "rooms": [
    {
      "type": "kitchen|bathroom|bedroom|living_room|hallway|dining_room|garage|terrace|unknown",
      "bbox": [x1, y1, x2, y2],
      "label": ""
    }
  ],
  "openings": [
    {"type": "door|sliding_door|window", "bbox": [x1, y1, x2, y2]}
  ],
  "image_dimensions": {"width": 0, "height": 0},
  "estimated_scale": "1:50"
}

OPENING DETECTION RULES:
- A door is a GAP in a wall line accompanied by a quarter-circle arc.
  The bbox wraps the gap + arc tightly.
- A sliding_door is a GAP in a wall line with parallel lines crossing it (no arc).
- A window is a GAP in a wall line with a short double line across the gap.
- ONLY mark openings at actual breaks/gaps in the black wall lines.
- If a bbox would not intersect any black line, do NOT include it.

bbox = [left, top, right, bottom] pixel coordinates. Return ONLY valid JSON."""


def _get_client() -> genai.Client:
    sa_path = os.path.abspath(
        os.path.join(os.path.dirname(__file__), "../../../../service_account.json")
    )
    if os.path.exists(sa_path):
        os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = sa_path
        return genai.Client(vertexai=True, project=VERTEX_PROJECT, location=VERTEX_LOCATION)
    return genai.Client(api_key=get_settings().gemini_api_key)


def _call_gemini_labeler(skeleton_b64: str) -> Any:
    """Send skeleton image to Gemini for semantic labeling only."""
    try:
        client = _get_client()
        image_bytes = base64.b64decode(skeleton_b64)
        response = client.models.generate_content(
            model=GEMINI_MODEL,
            contents=[
                types.Part.from_bytes(data=image_bytes, mime_type="image/png"),
                LABELING_PROMPT,
            ],
            config=types.GenerateContentConfig(
                temperature=1,
                max_output_tokens=24576,
                response_mime_type="application/json",
                thinking_config=types.ThinkingConfig(thinking_budget=0),
            ),
        )
        raw = response.text.strip() if response.text else ""
        try:
            return json.loads(raw)
        except json.JSONDecodeError as je:
            logger.warning(f"[gemini] JSON parse error: {je}")
            return {"error": f"JSON parse error: {je}", "raw_response": raw[:500]}
    except Exception as e:
        logger.error(f"[gemini] call failed: {e}")
        return {"error": str(e)}


async def process_floor_plan(
    image_b64: str,
    session_dir: Optional[Path] = None,
) -> Tuple[Any, Optional[str], int]:
    """
    Phase 1 pipeline — professional CV + AI labeling:

      [processing.py]
      1. Adaptive threshold → binary
      2. Morph close → seal wall gaps
      3. Erosion → destroy thin strokes (furniture < 3px)
      4. Dilation → restore wall thickness
      5. Skeletonize (scikit-image) → 1px wall axis
      6. HoughLinesP (min_len=3.5% diagonal) → long wall segments only
      → skeleton_b64 saved as debug_skeleton.png in session dir (visible in logs)

      [gemini_service.py]
      7. Gemini receives clean skeleton → labels rooms + opening gaps

      [processing.py]
      8. validate_openings: discard if area < 50px or < 2 sides touching wall_mask
      9. render_structural: white canvas + Hough wall lines (3px) + colored openings

    Returns: (metadata, structural_image_b64, processing_time_ms)
    """
    start = time.monotonic()
    loop = asyncio.get_event_loop()

    # Step 1-6: CV pre-processing (sync, fast ~100-300ms)
    logger.info("[phase1] starting CV pre-processing...")
    skeleton_b64, wall_lines, wall_mask, image_shape = await loop.run_in_executor(
        None,
        lambda: build_wall_skeleton(image_b64, debug_dir=session_dir),
    )
    logger.info(f"[phase1] skeleton ready: {len(wall_lines)} wall segments, shape={image_shape}")

    # Step 7: Gemini labeling on clean skeleton (~10-20s)
    logger.info("[phase1] calling Gemini labeler...")
    metadata = await loop.run_in_executor(None, _call_gemini_labeler, skeleton_b64)
    logger.info(
        f"[phase1] Gemini result: rooms={len(metadata.get('rooms', []))}, "
        f"openings={len(metadata.get('openings', []))}, "
        f"error={metadata.get('error')}"
    )

    # Step 8: validate openings against wall_mask
    if "error" not in metadata:
        metadata = await loop.run_in_executor(
            None, validate_openings, metadata, wall_mask
        )

    # Step 9: render from Hough lines + validated openings (no original pixels)
    structural_b64 = await loop.run_in_executor(
        None, render_structural, wall_lines, image_shape, metadata
    )

    elapsed_ms = int((time.monotonic() - start) * 1000)
    logger.info(f"[phase1] done in {elapsed_ms}ms")
    return metadata, structural_b64, elapsed_ms
